version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  slack: circleci/slack@4.1.3 

workflows:
  build:
    jobs:
      - build-core:
          context:
              - Build Context (Low Security)
      - security-scan-core:
          requires:
            - build-core
          context:
              - SecurityTesting Context
          filters:
              branches:
                only:
                  - develop 

jobs:
  build-core:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          BUNDLER_VERSION: 2.1.4
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install dependencies & run specs 
          command:  | 
            gem update --system
            gem install bundler:2.1.4
            INTRIGUE_ENV=test bundle install
            INTRIGUE_ENV=test bundle exec rake setup
            INTRIGUE_ENV=test bundle exec rake db:migrate
            INTRIGUE_ENV=test bundle exec rspec spec/*.rb
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here Job *${CIRCLE_JOB}* in branch `<< pipeline.git.branch >>` by committer ${CIRCLE_USERNAME} has *failed* :warning:. View job <${CIRCLE_BUILD_URL}|here>."
                  }
                }
              ]
            }
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Job *${CIRCLE_JOB}* in branch `<< pipeline.git.branch >>` by committer ${CIRCLE_USERNAME} successful :white_check_mark:. View job <${CIRCLE_BUILD_URL}|here>."
                  }
                }
              ]
            }
  security-scan-core:
    docker:
      - image: circleci/ruby:2.7.2-browsers
    steps:
      - checkout
      - run:
          name: Run whitesource
          command:  | 
            bundle install
            curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
            echo Unified Agent downloaded successfully
            java -jar wss-unified-agent.jar -project intrigue-core -d ./
    